version: "3.8"
services:
  db:
    container_name: commerceserver
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 5432:5432

  web:
    container_name: commerceapi
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./src/.env
    depends_on:
      - db

